apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: togglemaster
  labels:
    app: targeting-service
spec:
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
  selector:
    app: targeting-service
  type: ClusterIP

